### ISSUE TITLE
プロット動画と通常の動画を重ねたい

### ISSUE THREAD

**Issue by kosuke-kitahara** [sh-tatsuno/sports-analytics#9]
ウィンドウ２つだと見づらいので、ウイイレっぽくしたい

参考↓

https://www.tech-tech.xyz/clip_image.html

https://www.tech-tech.xyz/opencv-alphablend.html

**Comment by kosuke-kitahara** [comment]
着手中

**Comment by sh-tatsuno** [comment]
検証できる・邪魔にならない

**Comment by kosuke-kitahara** [comment]
| 動画 | 
| 平面 |

**Comment by kosuke-kitahara** [comment]
`動画` は囲ってないほうが良い

**Comment by kosuke-kitahara** [comment]
done
